# Generated by Django 4.2.6 on 2023-10-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapcord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
