# Generated by Django 4.2.6 on 2023-11-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapcord', '0002_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
