# Generated by Django 4.2.6 on 2023-11-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='important_post',
            field=models.BooleanField(default=False),
        ),
    ]
